language: go
go:
  - 1.11.x
  - master
env:
  - GO111MODULE=on
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
