language: go
go:
  - 1.11.x
  - 1.12.x
  - master
matrix:
  allow_failures:
    - go: master
env:
  - GO111MODULE=on
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: make dist
    on:
      tags: true
      go: 1.12.x
      condition: $TRAVIS_OS_NAME = linux
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
