name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Go test
      run: go test -v ./... -coverprofile=coverage.out -covermode=count
    - name: Run octocov
      uses: k1LoW/octocov-action@v0
